#!/usr/bin/env bash
#
# Copyright (c) 2025-2026 Corey Goldberg (https://github.com/cgoldberg)
#
# git-info - show info about repository
#
# instructions:
#  - add this script to a directory on your PATH
#  - make this script executable (chmod +x git-info)
#  - run 'git info' from any directory in a local git repo

set -eo pipefail


die () {
    tput bold; tput setaf 1; echo -en "\u2717 " 1>&2; tput sgr0
    tput bold; echo "$*" 1>&2; tput sgr0
    exit 1
}

indent () {
    cat - | sed -e 's/^[[:space:]]*/   /g'
}

if [ ! -x "$(type -pP git)" ]; then
    die "fatal: can't find git"
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    die "fatal: not a git repository"
fi

# traverse up to root of repo
while [[ ! -d .git ]] && [[ ! $(pwd) = "/" ]]; do
    cd ..
done

current_branch="$(\
    git branch --show-current \
)"
num_commits="$(\
    git rev-list --count "${current_branch}" \
        | numfmt --grouping \
)"
size_on_disk="$(\
    du -hs \
        | awk '{print $1}' \
)"
size_tracked_files="$(\
    git ls-files \
        | xargs -n 1 stat -c %s \
        | awk '{total+=$1} END {printf("%.0f\n", total)}' \
        | numfmt --to=iec \
)"
num_files="$(\
    find . -type f ! -path './.git/*' \
        | wc -l \
)"
num_tracked_files="$(\
    git ls-files \
        | wc -l \
)"
lines_tracked_files="$(\
    git grep -Il --no-color --no-untracked "" \
        | xargs -n 1 cat \
        | grep -c ^ \
        | numfmt --grouping \
)"
file_counts_by_extension="$(\
    find . -type f ! -path './.git/*' -name '*.*' -print0 \
        | xargs -0 -n 1 basename \
        | grep -v '^[\.]' \
        | sed 's/.*\.//' \
        | sort \
        | uniq -c \
        | sort -nr \
        | numfmt --grouping \
)"

echo
echo -e "\033[1;36m== Stats (branch: ${current_branch}) ==\033[0m"
echo "Commits: ${num_commits}" | indent
echo "Size on disk: ${size_on_disk}" | indent
echo "Size of tracked files: ${size_tracked_files}" | indent
echo "Files: ${num_files} (excluding .git directory)" | indent
echo "Tracked files: ${num_tracked_files}" | indent
echo "Lines in non-binary tracked files: ${lines_tracked_files}" | indent
echo "Files by extension:" | indent
echo "${file_counts_by_extension}"
echo
echo -e "\033[1;36m== Remotes ==\033[0m"
git remote -v | indent
echo
echo -e "\033[1;36m== Remote Branches ==\033[0m"
git branch -r --color=never | indent
echo
echo -e "\033[1;36m== Local Branches ==\033[0m"
git branch --color=never | indent
echo
