#!/usr/bin/env bash
#
# Copyright (c) 2025-2026 Corey Goldberg (https://github.com/cgoldberg)
# License: MIT
#
# git-sync - rebase all local branches in current repository from remote tracking branches
#
# - fetches from remote and prunes stale refs
# - creates a local tracking branch for every remote branch
# - stashes uncommitted changes
# - switches to default branch and does pull/rebase
# - switches to every other local branch and does pull/rebase
# - switches back to original branch
# - reapplies stashed changes
#
# requires:
#  - git (https://git-scm.com)
#
# instructions:
#  - add this script to a directory on your PATH
#  - make this script executable (chmod +x git-sync)
#  - run 'git sync' from any directory in a local git repo


BOLD="\e[1m"
GREEN="\e[32m"
RED="\e[31m"
RESET="\e[0m"
CHECK="\u2713"
CROSS="\u2717"

die() {
    printf "${BOLD}${RED}%b${RESET} ${BOLD}%s${RESET}\n" "${CROSS}" "$*" 1>&2
    exit 1
}

ok() {
    printf "${BOLD}${GREEN}%b${RESET} ${BOLD}%s${RESET}\n" "${CHECK}" "$*" 1>&2
}

if ! type git >/dev/null 2>&1; then
    die "fatal: can't find git"
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    die "fatal: not a git repository"
fi

sync_branch() {
    echo "switching to branch '$1'"
    git checkout --quiet "$1"
    echo "updating '$1'"
    git pull --rebase --stat
}

echo
echo "fetching refs ..."
echo
git fetch --all --prune --verbose

default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's/.*\///')

for remote_branch in $(git branch --all --no-color | grep remotes | grep -v "${default_branch}"); do
    branch="${remote_branch#remotes/origin/}"
    git branch --track "${branch}" "${remote_branch}" 2>&1 | grep -v "already exists"
done
echo

current_branch=$(git branch --show-current)
branches=( $(git branch --format="%(refname:short)") )
branches_without_default=( ${branches[@]/${default_branch}} )

git stash --quiet
sync_branch "${default_branch}"
echo
for branch in "${branches_without_default[@]}"; do
    sync_branch "${branch}"
    echo
done
git checkout --quiet "${current_branch}"
git stash pop --quiet 2>/dev/null || true

ok "done syncing branches"
