#!/usr/bin/env bash
#
# Copyright (c) 2025-2026 Corey Goldberg (https://github.com/cgoldberg)
#
# git-syncrepo - sync branches in remote fork with main branch in parent repo
#
# - fetches from remote and prunes stale refs
# - creates a local tracking branch for every remote branch (if -a option is used)
# - syncs current branch in remote fork with main branch in parent repo (all branches if -a option is used)
# - only works if inside a local git repo that was cloned from a fork on GitHub
# - requires GitHub CLI (https://github.com/cli/cli/blob/trunk/docs/install_linux.md)
# - must have parent repo set as default remote (run 'gh repo set-default')
#
# requires:
#  - git (https://git-scm.com)
#
# instructions:
#  - set an environment variable named 'GITHUB_USERNAME' with your GitHub
#    account name (i.e.: 'export GITHUB_USERNAME=cgoldberg')
#  - run 'gh repo set-default' and set parent repo as default remote
#  - add this script to a directory on your PATH
#  - make this script executable (chmod +x git-syncrepo)
#  - run 'git syncrepo' from any directory in a local git repo
#
# usage/examples:
#  - $ git syncrepo  # default branch only
#  - $ git syncrepo -a  # all branches


die () {
    tput bold; tput setaf 1; echo -en "\u2717 " 1>&2; tput sgr0
    tput bold; echo "$*" 1>&2; tput sgr0
    exit 1
}

ok () {
    tput bold; tput setaf 10; echo -en "\u2714  " 1>&2; tput sgr0
    tput bold; echo "$*" 1>&2; tput sgr0
}

while getopts ":ah" opt; do
    case "${opt}" in
        a )
            OPT_ALL_BRANCHES="true"
            ;;
        h )
            echo -e "sync branches in remote fork with main branch in parent repo\n\n"\
                "options:\n"\
                " -a : sync all branches\n"\
                " -h : show this help message"
            exit
            ;;
        \? )
            die "invalid option"
            ;;
    esac
done

if ! type git >/dev/null 2>&1; then
    die "fatal: can't find git"
fi

if ! type gh >/dev/null 2>&1; then
    die "fatal: can't find GitHub CLI"
fi

if [ -z "${GITHUB_USERNAME}" ]; then
    die "fatal: 'GITHUB_USERNAME' environment variable not set"
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    die "fatal: not a git repository"
fi

if ! git remote --verbose | grep -q "github\.com"; then
    die "fatal: must have an origin on github.com"
fi

repo_name="$(basename $(basename $(git remote get-url origin)) '.git')"
repo="${GITHUB_USERNAME}/${repo_name}"

if [[ "$(gh repo view "${repo}" --json isFork 2>/dev/null)" != *"true"* ]]; then
    die "fatal: '${repo_name}' is not a fork"
fi

parent_repo=$(gh repo set-default --view 2>/dev/null)

if [ -z "${parent_repo}" ]; then
    die "fatal: remote repo is not set (run 'gh repo set-default' and set the parent as default remote)"
fi

if [ "${repo}" == "${parent_repo}" ]; then
    die "fatal: parent repo is not the default remote (run 'gh repo set-default' and set the parent as default remote)"
fi

sync_parent_branch () {
    echo -e "syncing '$1' branch in remote fork with main branch in parent repo ...\n"
    if gh repo sync "${repo}" --branch "$1" >/dev/null; then
        ok "synced '${GITHUB_USERNAME}:$1' branch from '${parent_repo%%/*}:${default_branch}'"
    fi
}

default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's/.*\///')

if [ -n "${OPT_ALL_BRANCHES}" ]; then
    for remote_branch in $(git branch --all --no-color | grep remotes | grep -v "${default_branch}"); do
        branch="${remote_branch#remotes/origin/}"
        git branch --track "${branch}" "${remote_branch}" 2>&1 | grep -v "already exists"
    done
    echo
fi

current_branch=$(git branch --show-current)
branches=( $(git branch --format='%(upstream:short)' | grep origin | awk -F '/' '{print $NF}') )
branches_without_current=( ${branches[@]/${current_branch}} )

sync_parent_branch "${current_branch}"
echo
if [ -n "${OPT_ALL_BRANCHES}" ]; then
    for branch in "${branches_without_current[@]}"; do
        sync_parent_branch "${branch}"
        echo
    done
fi
