#!/usr/bin/env bash
#
# Copyright (c) 2025-2026 Corey Goldberg (https://github.com/cgoldberg)
# License: MIT
#
# git-track-branches - create a local tracking branch for every remote branch
#
# requires:
#  - git (https://git-scm.com)
#
# instructions:
#  - add this script to a directory on your PATH
#  - make this script executable (chmod +x git-track-branches)
#  - run 'git track-branches' from any directory in a local git repo


BOLD="\e[1m"
GREEN="\e[32m"
RED="\e[31m"
RESET="\e[0m"
CHECK="\u2713"
CROSS="\u2717"

die() {
    printf "${BOLD}${RED}%b${RESET} ${BOLD}%s${RESET}\n" "${CROSS}" "$*" 1>&2
    exit 1
}

ok() {
    printf "${BOLD}${GREEN}%b${RESET} ${BOLD}%s${RESET}\n" "${CHECK}" "$*" 1>&2
}

if ! type git >/dev/null 2>&1; then
    die "fatal: can't find git"
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    die "fatal: not a git repository"
fi

git fetch --all --prune --verbose
echo

default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's/.*\///')
remote_branches_without_default=( $(git branch --all --no-color | grep remotes | grep -v "${default_branch}") )

if [ ${#remote_branches_without_default[@]} -eq 0 ]; then
    die "no remote branches to track (only '${default_branch}' exists)"
fi

for remote_branch in ${remote_branches_without_default[@]}; do
    branch="${remote_branch#remotes/origin/}"
    git branch --track "${branch}" "${remote_branch}" 2>&1 | grep -v "already exists"
done

echo
ok "done creating local tracking branches"
